name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ejecutar en cada push a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Compilar proyecto
        run: |
          ./gradlew assemble  # Ejemplo con Gradle, ajustar según el sistema de construcción

      - name: Ejecutar pruebas unitarias
        run: |
          ./gradlew test  # Comando para ejecutar pruebas unitarias

      - name: Análisis de código
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
